---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((image/genesis.url))
    tag:        ((image/genesis.tag))

inputs:
- name: git
  path: kit
- name: git-ci

run:
  path: git-ci/ci/tasks/test-flight/task

params:
  GENESIS_HONOR_ENV:    1
  GIT_EMAIL:            ((github.email))
  GIT_NAME:             ((github.name))
  VAULT_URI:            ((vault.url))
  VAULT_TOKEN:          ((vault.token))
  KIT_SHORTNAME:        cf-app-autoscaler
  BOSH_ENVIRONMENT:     ((bosh.uri))
  BOSH_CA_CERT:         ((bosh.ca))
  BOSH_CLIENT:          ((bosh.username))
  BOSH_CLIENT_SECRET:   ((bosh.password))
