#!/bin/bash
set -eu

header() {
	echo
	echo "###############################################"
	echo
	echo $*
	echo
}

cleanup() {
	for deployment in "$@"; do
		echo "> deleting ${deployment}"
		$BOSH -n -d "${deployment}" delete-deployment

		for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
			echo "  - removing disk ${disk}"
			$BOSH -n delete-disk "${disk}"
		done
	done
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

### Removing cleanup procedure prior to deployment to address 
### liquibase.exception.DatabaseException race condition
#header "Cleaning up from any previous deployments (if necessary)..."
#cleanup ci-baseline-${KIT_SHORTNAME}
#safe rm -rf secret/ci/baseline/${KIT_SHORTNAME}

# Create a cf deployment to be used from cf-app-autoscaler
cd ..
mkdir -p cf
cd cf
genesis init --kit cf/1.10.7 -d ci-baseline-v2-cf

header "Deploying BASELINE environment to verify functionality..."
cd dev
# make sure hooks are executable before screaming at shipit for failing.
genesis compile-kit --name ${KIT_SHORTNAME} -v 9.9.9 --force
cd ..
genesis add-secrets ci-baseline
genesis deploy -y ci-baseline
$BOSH -d ci-baseline-${KIT_SHORTNAME} instances --ps

header "Testing addons..."
genesis do ci-baseline -- bind-autoscaler
genesis do ci-baseline -- setup-cf-plugin -f

cleanup ci-baseline-${KIT_SHORTNAME}
safe rm -rf secret/ci/baseline/${KIT_SHORTNAME}