---
kit:
  features:
  - external-db
  - mysql

genesis:
  env: params

params:
  cf_deployment_env:   base-test
  cf_deployment_type:  cf
  cf_core_network:     cf-core-network
  cf_system_domain:    cf.lab.example.com
  skip_ssl_validation: true
  db_disk_type:        20GB
  stemcell_os:         ubuntu-jammy

bosh-variables:
  database:
    host:     external-mysql-host.lab.example.com
    port:     3377
    scheme:   mysql
    name:     cfas
    username: as
    password: '$up3r$ecr!t'
    sslmode:  allow
    tls.ca:   <!database.tla.ca!>
