---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((image/concourse_go.url))
    tag:        ((image/concourse_go.tag))

inputs:
- name: git
- name: git-ci

run:
  path: git-ci/ci/tasks/spec-tests/task
