---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((image/genesis.url))
    tag:        ((image/genesis.tag))

inputs:
- name: version
- name: git
- name: git-ci

outputs:
- name: gh
- name: notifications
- name: pushme

params:
  REPO_ROOT:        git
  VERSION_FROM:     version/number
  RELEASE_ROOT:     gh
  NOTIFICATION_OUT: notifications
  BRANCH:           master
  GITHUB_OWNER:     genesis-community
  GIT_EMAIL:        ((github.email))
  GIT_NAME:         ((github.name))
  KIT_SHORTNAME:    cf-app-autoscaler

run:
  path: git-ci/ci/tasks/shipit/task
