api_client_id: <!{credhub}:api_client_id!>
api_client_secret: <!{credhub}:api_client_secret!>
apiserver_monitor_basic_auth_password: <!{credhub}:apiserver_monitor_basic_auth_password!>
apiserver_server_cert:
    ca: <!{credhub}:apiserver_server_cert.ca!>
    certificate: <!{credhub}:apiserver_server_cert.certificate!>
    private_key: <!{credhub}:apiserver_server_cert.private_key!>
app_autoscaler_ca_cert:
    ca: <!{credhub}:app_autoscaler_ca_cert.ca!>
    certificate: <!{credhub}:app_autoscaler_ca_cert.certificate!>
    private_key: <!{credhub}:app_autoscaler_ca_cert.private_key!>
app_autoscaler_sbss_restricted_dbuser_password: <!{credhub}:app_autoscaler_sbss_restricted_dbuser_password!>
app_autoscaler_sbss_restricted_dbuser_password_blue: <!{credhub}:app_autoscaler_sbss_restricted_dbuser_password_blue!>
auditlog_monitor_basic_auth_password: <!{credhub}:auditlog_monitor_basic_auth_password!>
autoscaler_eventgenerator_health_password: <!{credhub}:autoscaler_eventgenerator_health_password!>
autoscaler_metricsforwarder_health_password: <!{credhub}:autoscaler_metricsforwarder_health_password!>
autoscaler_operator_health_password: <!{credhub}:autoscaler_operator_health_password!>
autoscaler_scalingengine_health_password: <!{credhub}:autoscaler_scalingengine_health_password!>
autoscaler_scheduler_health_password: <!{credhub}:autoscaler_scheduler_health_password!>
autoscaler_service_broker_password: <!{credhub}:autoscaler_service_broker_password!>
dashboard_client_id: <!{credhub}:dashboard_client_id!>
dashboard_client_secret: <!{credhub}:dashboard_client_secret!>
dashboard_monitor_basic_auth_password: <!{credhub}:dashboard_monitor_basic_auth_password!>
eventgenerator_client_cert:
    ca: <!{credhub}:eventgenerator_client_cert.ca!>
    certificate: <!{credhub}:eventgenerator_client_cert.certificate!>
    private_key: <!{credhub}:eventgenerator_client_cert.private_key!>
eventgenerator_monitor_basic_auth_password: <!{credhub}:eventgenerator_monitor_basic_auth_password!>
eventgenerator_server_cert:
    ca: <!{credhub}:eventgenerator_server_cert.ca!>
    certificate: <!{credhub}:eventgenerator_server_cert.certificate!>
    private_key: <!{credhub}:eventgenerator_server_cert.private_key!>
log_cache_syslog_tls_ca:
    ca: <!{credhub}:log_cache_syslog_tls_ca.ca!>
    certificate: <!{credhub}:log_cache_syslog_tls_ca.certificate!>
    private_key: <!{credhub}:log_cache_syslog_tls_ca.private_key!>
loggr_syslog_agent_cache_tls:
    ca: <!{credhub}:loggr_syslog_agent_cache_tls.ca!>
    certificate: <!{credhub}:loggr_syslog_agent_cache_tls.certificate!>
    private_key: <!{credhub}:loggr_syslog_agent_cache_tls.private_key!>
loggr_syslog_agent_metrics:
    ca: <!{credhub}:loggr_syslog_agent_metrics.ca!>
    certificate: <!{credhub}:loggr_syslog_agent_metrics.certificate!>
    private_key: <!{credhub}:loggr_syslog_agent_metrics.private_key!>
loggr_syslog_agent_tls:
    ca: <!{credhub}:loggr_syslog_agent_tls.ca!>
    certificate: <!{credhub}:loggr_syslog_agent_tls.certificate!>
    private_key: <!{credhub}:loggr_syslog_agent_tls.private_key!>
loggr_syslog_binding_cache_api_tls:
    ca: <!{credhub}:loggr_syslog_binding_cache_api_tls.ca!>
    certificate: <!{credhub}:loggr_syslog_binding_cache_api_tls.certificate!>
    private_key: <!{credhub}:loggr_syslog_binding_cache_api_tls.private_key!>
loggr_syslog_binding_cache_metrics:
    ca: <!{credhub}:loggr_syslog_binding_cache_metrics.ca!>
    certificate: <!{credhub}:loggr_syslog_binding_cache_metrics.certificate!>
    private_key: <!{credhub}:loggr_syslog_binding_cache_metrics.private_key!>
loggr_syslog_binding_cache_tls:
    ca: <!{credhub}:loggr_syslog_binding_cache_tls.ca!>
    certificate: <!{credhub}:loggr_syslog_binding_cache_tls.certificate!>
    private_key: <!{credhub}:loggr_syslog_binding_cache_tls.private_key!>
loggregator_ca:
    ca: <!{credhub}:loggregator_ca.ca!>
    certificate: <!{credhub}:loggregator_ca.certificate!>
    private_key: <!{credhub}:loggregator_ca.private_key!>
loggregator_tls_agent:
    ca: <!{credhub}:loggregator_tls_agent.ca!>
    certificate: <!{credhub}:loggregator_tls_agent.certificate!>
    private_key: <!{credhub}:loggregator_tls_agent.private_key!>
metriccollector_monitor_basic_auth_password: <!{credhub}:metriccollector_monitor_basic_auth_password!>
metricscollector_ca:
    ca: <!{credhub}:metricscollector_ca.ca!>
    certificate: <!{credhub}:metricscollector_ca.certificate!>
    private_key: <!{credhub}:metricscollector_ca.private_key!>
metricscollector_client:
    ca: <!{credhub}:metricscollector_client.ca!>
    certificate: <!{credhub}:metricscollector_client.certificate!>
    private_key: <!{credhub}:metricscollector_client.private_key!>
metricscollector_server:
    ca: <!{credhub}:metricscollector_server.ca!>
    certificate: <!{credhub}:metricscollector_server.certificate!>
    private_key: <!{credhub}:metricscollector_server.private_key!>
metricsforwarder_autoscaler_metricsforwarder_loggregator_tls:
    ca: <!{credhub}:metricsforwarder_autoscaler_metricsforwarder_loggregator_tls.ca!>
    certificate: <!{credhub}:metricsforwarder_autoscaler_metricsforwarder_loggregator_tls.certificate!>
    private_key: <!{credhub}:metricsforwarder_autoscaler_metricsforwarder_loggregator_tls.private_key!>
metricsforwarder_monitor_basic_auth_password: <!{credhub}:metricsforwarder_monitor_basic_auth_password!>
operator_monitor_basic_auth_password: <!{credhub}:operator_monitor_basic_auth_password!>
postgres_ca:
    ca: <!{credhub}:postgres_ca.ca!>
    certificate: <!{credhub}:postgres_ca.certificate!>
    private_key: <!{credhub}:postgres_ca.private_key!>
postgres_client:
    ca: <!{credhub}:postgres_client.ca!>
    certificate: <!{credhub}:postgres_client.certificate!>
    private_key: <!{credhub}:postgres_client.private_key!>
postgres_server:
    ca: <!{credhub}:postgres_server.ca!>
    certificate: <!{credhub}:postgres_server.certificate!>
    private_key: <!{credhub}:postgres_server.private_key!>
ratelimiter_monitor_basic_auth_password: <!{credhub}:ratelimiter_monitor_basic_auth_password!>
scalingengine_client_cert:
    ca: <!{credhub}:scalingengine_client_cert.ca!>
    certificate: <!{credhub}:scalingengine_client_cert.certificate!>
    private_key: <!{credhub}:scalingengine_client_cert.private_key!>
scalingengine_monitor_basic_auth_password: <!{credhub}:scalingengine_monitor_basic_auth_password!>
scalingengine_server_cert:
    ca: <!{credhub}:scalingengine_server_cert.ca!>
    certificate: <!{credhub}:scalingengine_server_cert.certificate!>
    private_key: <!{credhub}:scalingengine_server_cert.private_key!>
scheduler_client_cert:
    ca: <!{credhub}:scheduler_client_cert.ca!>
    certificate: <!{credhub}:scheduler_client_cert.certificate!>
    private_key: <!{credhub}:scheduler_client_cert.private_key!>
scheduler_monitor_basic_auth_password: <!{credhub}:scheduler_monitor_basic_auth_password!>
scheduler_server_cert:
    ca: <!{credhub}:scheduler_server_cert.ca!>
    certificate: <!{credhub}:scheduler_server_cert.certificate!>
    private_key: <!{credhub}:scheduler_server_cert.private_key!>
service_broker_password: <!{credhub}:service_broker_password!>
service_broker_password_blue: <!{credhub}:service_broker_password_blue!>
servicebroker_server_cert:
    ca: <!{credhub}:servicebroker_server_cert.ca!>
    certificate: <!{credhub}:servicebroker_server_cert.certificate!>
    private_key: <!{credhub}:servicebroker_server_cert.private_key!>
syslog_agent_log_cache_tls:
    ca: <!{credhub}:syslog_agent_log_cache_tls.ca!>
    certificate: <!{credhub}:syslog_agent_log_cache_tls.certificate!>
    private_key: <!{credhub}:syslog_agent_log_cache_tls.private_key!>
uaa_client_id: <!{credhub}:uaa_client_id!>
uaa_secret: <!{credhub}:uaa_secret!>
