/secret/exodus/base-test/cf:
  system_domain: sys.test.cf.domain
  core_network: test-core-network
  app_autoscaler_client:  app-autoscaler-client
  app_autoscaler_secret:  app-autoscaler-secret
  kit_version: 2.5.2
  nats_client_cert: <!{credhub}:nats_client_cert.certificate!>
  nats_client_key: <!{credhub}:nats_client_cert.private_key!>
  log_cache_ca: <!{credhub}:log_cache_ca.certificate!>
  log_cache_cert: <!{credhub}:log_cache_client_cert.certificate!>
  log_cache_key: <!{credhub}:log_cache_client_cert.private_key!>
  diego_instance_identity_ca: <!{credhub}:diego_instance_identity_ca.certificate!>
