/secret/exodus/base/bosh:
  url: "https://bosh.lab.example.com:25555"
  admin_username: admin
  admin_password: admin-password
  ca_cert: "mycert"
  kit_name: bosh
  credhub_ca_cert: "credhubcacert"
  vault_base: /secret/base/bosh
/secret/exodus/external-db/bosh:
  url: "https://bosh.lab.example.com:25555"
  admin_username: admin
  admin_password: admin-password
  ca_cert: "mycert"
  kit_name: bosh
  credhub_ca_cert: "credhubcacert"
  vault_base: /secret/external-db/bosh
/secret/exodus/mysql/bosh:
  url: "https://bosh.lab.example.com:25555"
  admin_username: admin
  admin_password: admin-password
  ca_cert: "mycert"
  kit_name: bosh
  credhub_ca_cert: "credhubcacert"
  vault_base: /secret/mysql/bosh
/secret/exodus/params/bosh:
  url: "https://bosh.lab.example.com:25555"
  admin_username: admin
  admin_password: admin-password
  ca_cert: "mycert"
  kit_name: bosh
  credhub_ca_cert: "credhubcacert"
  vault_base: /secret/params/bosh
/secret/exodus/base-test/cf:
  system_domain: sys.test.cf.domain
  core_network: test-core-network
  app_autoscaler_client:  app-autoscaler-client
  app_autoscaler_secret:  app-autoscaler-secret
  admin_username: cf-admin
  admin_password: cf-admin-password
  kit_version: 2.5.2
  nats_client_cert: <!{credhub}:nats_client_cert.certificate!>
  nats_client_key: <!{credhub}:nats_client_cert.private_key!>
  log_cache_ca: <!{credhub}:log_cache_ca.certificate!>
  log_cache_cert: <!{credhub}:log_cache_client_cert.certificate!>
  log_cache_key: <!{credhub}:log_cache_client_cert.private_key!>
  diego_instance_identity_ca: <!{credhub}:diego_instance_identity_ca.certificate!>
