#!/bin/bash
shopt -s nullglob
set -eu

# Genesis Kit `blueprint' Hook

declare -a manifests

validate_features external-db

manifests=( upstream/templates/app-autoscaler-deployment.yml )
want_feature external-db && manifests+=( \
  "upstream/operations/external-db.yml" \
  "overlay/exernal-db.yml" \
)

# Do features => opsfiles stuff here
for __feature in $GENESIS_REQUESTED_FEATURES; do
  if [[ $__feature =~ operations/.* ]] ; then
    if [[ -f "upstream/$__feature.yml" ]] ; then
      manifests+=( "upstream/$__feature.yml" )
    else
      __bail "$GENSIS_KIT_ID does not support the $__feature feature"
    fi
  elif [[ -f $GENESIS_ROOT/ops/$__feature.yml ]] ; then
    mkdir -p "$(dirname "local_ops/$__feature.yml")"
    cp "$GENESIS_ROOT/ops/$__feature.yml" "local_ops/$__feature.yml"
    manifests+=( "local_ops/$__feature.yml" )
  else
    __bail "$GENESIS_KIT_ID does not support the $__feature feature"
  fi
done

manifests+=( \
  overlay/base.yml \
  overlay/change_deployment_and_network.yml \
  overlay/releases.yml \
)

echo "${manifests[@]}"
