#!/bin/bash

set -u

# Version check
min_version="3.0.9-rc.1"
genesis_version="$(genesis -v 2>&1 | grep '^Genesis v' | sed -e 's/Genesis v\(.*\) (.*$/\1/')"
if ! [[ "$genesis_version" =~ -dev$ ]] && ! new_enough "$genesis_version" "$min_version" ; then
  describe >&2 "" "#R{[ERROR]} This kit needs Genesis $min_version.  Please upgrade before continuing" ""
  exit 1
fi
set -e

cf_env="$(jq -r '.params.cf_deployment_env//.genesis.env' <<<"$GENESIS_ENVIRONMENT_PARAMS")"
cf_type="$(jq -r '.params.cf_deployment_type//"cf"' <<<"$GENESIS_ENVIRONMENT_PARAMS")"
cf_exodus="$(lookup --exodus-for "${cf_env}/${cf_type}" .)"

cc_ok=yes
# Cloud Config checks
if [[ -n "$GENESIS_CLOUD_CONFIG" ]] ; then
  if want_feature ocfp ; then
    _env_scale="$(lookup --partial meta.ocfp.env.scale)"
    # FIXME: what about the postgres/mysql instance groups
    jobs=( as-apiserver as-scalingengine as-scheduler as-operator as-eventgenerator as-metricsforwarder )
    for job in "${jobs[@]}" ; do
      _vm_type="${job}-${_env_scale}"
      _disk_type="${job}-${_env_scale}"
      _network="${GENESIS_ENVIRONMENT}-ocf"

      cloud_config_needs vm_type   "$(lookup params.vm_type   ${_vm_type})"
      cloud_config_needs network   "$(lookup params.network   ${_network})"
      cloud_config_needs disk_type "$(lookup params.disk_pool ${_disk_type})"
    done
  else # Legacy was hard coded
    for t in minimal small; do
      cloud_config_needs vm_type "$t"
    done
  fi

  # Check if there were any errors reported from the above checks.
  if check_cloud_config ; then
    describe "  cloud config [#G{OK}]"
  else
    describe "  cloud config [#R{FAILED}]"
    cc_ok=no
  fi
fi

# Runtime config checks
runtime_ok=yes

# Check for BOSH DNS
if ! rcq -e '.addons[] | .name | select(. == "bosh-dns")' &>/dev/null; then
  runtime_ok=no
  describe >&2 \
    "  #R{Errors were found} in your runtime-config:" \
    "    - #R{BOSH DNS is not in the runtime-config, which is required. Refer to}" \
    "      #R{'genesis man $GENESIS_ENVIRONMENT' for more info.}" ""
fi

# Check if there were any errors reported from runtime config checks
if [[ "$runtime_ok" == "yes" ]]; then
  describe "  runtime config [#G{OK}]"
else
  describe "  runtime config [#R{FAILED}]"
fi

cf_kit_version="$(jq -r .kit_version <(echo "$cf_exodus"))"
[[ -n "$cf_kit_version" ]] || bail "#R{[ERROR]} Could not determine kit version with associated CF deployment"
if new_enough "$cf_kit_version" 2.5.2 ; then
  genesis_log "  target cf kit version [#G{OK}]"
else
  echo "" >&2
  genesis_log @error "This version of autoscaler kit requires CF Kit 2.5.2 or greater to be deployed as its target CF." ""
  exit 1
fi

env_ok=yes
# Environment Parameter checks - none yet!

if [[ "$env_ok" == "yes" ]]; then
  describe "  environment files [#G{OK}]"
else
  describe "  environment files [#R{FAILED}]"
fi

if [[ "$env_ok" == "no" || "$cc_ok" == "no" || "$runtime_ok" == no ]] ; then
  exit 1
fi


