---
meta:
  # NOTE: vvv next genesis rc will have these 3  built in, remove then
  vault_env:    (( grab $GENESIS_SECRETS_SLUG ))
  vault_mount:  (( grab $GENESIS_SECRETS_MOUNT ))
  vault_exodus: (( grab $GENESIS_EXODUS_MOUNT ))
  # NOTE: ^^^

  ocfp:
    env:
      scale: (( grab params.env.scale || "dev" ))

    vault:
      tf:    (( concat meta.vault_mount "tf/" meta.vault_env ))

    certs:
      trusted:
        - (( vault meta.vault_mount "/certs/org:ca" )) # Organization CA, if exists
        - (( vault meta.vault_mount "/certs/dbs:ca" )) # External Databases CA

  db:
    hostname: (( vault meta.ocfp.vault.tf "/dbs/autoscaler:hostname" ))
    port:     (( vault meta.ocfp.vault.tf "/dbs/autoscaler:port"     ))
    scheme:   (( vault meta.ocfp.vault.tf "/dbs/autoscaler:scheme"   ))
    database: (( vault meta.ocfp.vault.tf "/dbs/autoscaler:database" ))
    username: (( vault meta.ocfp.vault.tf "/dbs/autoscaler:username" ))
    password: (( vault meta.ocfp.vault.tf "/dbs/autoscaler:password" ))
    sslmode:  "verify-ca"
    ca:       (( vault meta.ocfp.vault.tf "/dbs/autoscaler:ca"       ))

  cf:
    exodus:          (( concat meta.vault_exodus genesis.env "/cf" ))
    deployment_name: (( concat genesis.env "-cf" ))

