---
meta:
  env_name:          (( grab $GENESIS_ENVIRONMENT ))
  env_slug:          (( grab $GENESIS_SECRETS_SLUG ))
  env_scale:         (( grab params.env_scale || "dev" ))
  vault_mount:       (( grab $GENESIS_SECRETS_MOUNT ))
  vault_exodus_path: (( grab $GENESIS_EXODUS_MOUNT ))
  vault_tf_path:     (( concat meta.vault_mount "tf/" meta.env_slug ))
  vault_env_path:    (( concat meta.vault_mount meta.env_slug ))
  vault_certs_path:  (( concat meta.vault_mount "certs" ))

  trusted_certs:
    - (( vault meta.vault_certs_path "/org:ca" )) # Organization CA, if exists
    - (( vault meta.vault_certs_path "/dbs:ca" )) # External Databases CA

  db:
    hostname: (( vault meta.vault_tf_path "/dbs/autoscaler:hostname" ))
    port:     (( vault meta.vault_tf_path "/dbs/autoscaler:port"     ))
    scheme:   (( vault meta.vault_tf_path "/dbs/autoscaler:scheme"   ))
    database: (( vault meta.vault_tf_path "/dbs/autoscaler:database" ))
    username: (( vault meta.vault_tf_path "/dbs/autoscaler:username" ))
    password: (( vault meta.vault_tf_path "/dbs/autoscaler:password" ))
    sslmode:  "verify-ca"
    ca:       (( vault meta.vault_tf_path "/dbs/autoscaler:ca"       ))

  cf:
    exodus:          (( concat meta.vault_exodus_path meta.env_name "/cf" ))
    deployment_name: (( concat meta.env_name "-cf" ))

