---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((image/genesis.url))
    tag:        ((image/genesis.tag))

inputs:
- name: git
- name: git-ci
- name: git-latest-tag

run:
  path: git-ci/ci/tasks/spec-check/task
