---
meta:
  kit:     cf-app-autoscaler
  release: CF App Autoscaler Genesis Kit
  target:  pipes/genesis
  url:     https://pipes.scalecf.net
  iaas:    vsphere
  exposed: no
  initial_version: 1.0.0

  upstream:
    manifest:
      package: app-autoscaler
      repo:    cloudfoundry/app-autoscaler-release
      path:    upstream
      filter:
      - templates/*
      - operations/*

    bosh_releases:
    - name:       app-autoscaler
      type:       github-release
      repository: cloudfoundry/app-autoscaler-release
      path:       overlay/releases/app-autoscaler.yml
      access_token: ((github.access_token))

  bosh:
    uri:      ((bosh.uri))
    username: ((bosh.username))
    password: ((bosh.password))
    cacert:   ((bosh.ca))

  vault:
    url:       ((vault.url))
    token:     ((vault.token))

  aws:
    access_key: ((cloudfoundry-community-aws.access_key_id))
    secret_key: ((cloudfoundry-community-aws.secret_access_key))

  github:
    owner:        genesis-community
    repo:         cf-app-autoscaler-genesis-kit
    branch:       develop
    main-branch:  main
    private_key:  ((github.private_key))
    access_token: ((github.access_token))
    name:         ((github.name))
    email:        ((github.email))

  shout:
    url:      ((shout.url))
    username: ((shout.username))
    password: ((shout.password))
