---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ((image/concourse_go.url))
    tag:        ((image/concourse_go.tag))

inputs:
- name: git
- name: git-ci
- name: bosh-release

outputs:
- name: pushme

run:
  path: git-ci/ci/tasks/update-bosh-release/task

params:
  OPS_FILE_PATH:
  RELEASE_NAME:
  BRANCH:           master
  GITHUB_OWNER:     genesis-community
  GIT_EMAIL:        ((github.email))
  GIT_NAME:         ((github.name))
